import Head from "next/head";

const Navbar = () => {
    return(
        <>
        <Head>
            <title>My Tech School Project</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="navbar bg-success text-success-content">
            <div className="flex-1">
                <a className="btn btn-ghost normal-case text-xl">My School</a>
            </div>
        </div>
        </>
    )
}

export default Navbar;